#!/opt/local/bin/node

var fs = require('fs');
var util = require('util');
var generator = require('./pegjs-generator');

var argv = process.argv;
if (argv.length === 4) {
    fs.readFile(argv[2],
                function(err, input) {
                    input = '' + input;
                    json = JSON.parse(input);
                    util.print(json);
                });
}