#!/opt/local/bin/node

var fs = require('fs');
var util = require('util');
var js = require('./ex-javascript-parser');

var argv = process.argv;
for (var i = 2; i < argv.length; i++) {
    fs.readFile(argv[i],
        function (err, input) {
            input = '' + input;
            try {
                var tree = js.parse(input, 'start');
                util.print(JSON.stringify(tree, null, 2));
            } catch (e) {
                util.print("Line " + e.line + ", column " + e.column + ": " + e.message + "\n");
            }
            
        });
}
